### ISSUE TITLE
Order of months in the month list displayed in the select box is wrong.

### ISSUE THREAD

**Issue by himavijayachandran** [katemihalikova/ion-datetime-picker#20] opened 2016-04-26 05:34 UTC
Order of months in the month list displayed in the select box is wrong.
November and December come in between February and March.

**Comment by katemihalikova** [comment] 2016-04-26 05:37
Working fine on all of my devices, please provide more details.

**Comment by himavijayachandran** [comment] 2016-04-26 05:49
I want to develop an application that should work from at least android 4.4 on wards.

**Comment by katemihalikova** [comment] 2016-04-26 06:03
Thanks for your reply, but I need to isolate your problem and thus I need a simple example snippet extracted from your app that demonstrates your problem. You can start with the codepen demo. Feel free to reopen this issue when you are done.

**Comment by spi7fire** [comment] 2016-06-15 10:20
![image](https://cloud.githubusercontent.com/assets/2589702/16076416/e6ea7f0c-32fb-11e6-84fd-d5d0cea4526b.png)

Happens to me too, both on web and on IOS
months sorting is wrong

**Comment by spi7fire** [comment] 2016-06-15 11:48
Do you have a working example in codepen that i could see and compare with
my code?
I am using Ionic 1.7.15 angular v1.3.13

The problem is with ordering the month list, i tried fixing it by myslef
and failed to do so, maybe you can suggest
This line:
*<select ng-model="bind.month" ng-options="index as month for (index,
month) in i18n.months" ng-change="change('month')"></select>*
Should have an " *| OrderBy: Number(index) *" or something alike. inside
the ng-options (i guess its not index that should be inside the orderBy)



On Wed, Jun 15, 2016 at 2:14 PM, Kate Miháliková <notifications@github.com>
wrote:

> Could you please add a codepen demonstrating your issue or at least your
> ionic and angular version? Thanks.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/katemihalikova/ion-datetime-picker/issues/20#issuecomment-226158051>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACeEBr1PfSxS1qJGbA7ESxQMUsJm5icSks5qL96ygaJpZM4IPm9r>
> .
>



-- 
בברכה,
עופר שפירא
054-4978633
<http://www.dailys.co.il/>

**Comment by katemihalikova** [comment] 2016-06-16 06:31
There is a demo in readme: http://codepen.io/katemihalikova/pen/dYvjzP
When I get some free time I'm going to look into it if I'm able to reproduce with your angular version.

**Comment by katemihalikova** [comment] 2016-07-20 07:14
OK I've reproduced it recently with the angular version you are using. I will try to come up with a solution soon.

*Workaround:* use ionic `>=1.1.0`

**Comment by katemihalikova** [comment] 2016-07-20 08:34
Fixed by 4c8611f and released as `0.3.1`.

**Closed by katemihalikova** 2016-07-20 08:34 UTC
Labels: bug, in progress

**Comment by spi7fire** [comment] 2016-07-20 08:52
Thanks!!
