### ISSUE TITLE
Reset to default values

### ISSUE THREAD

**Issue by incansoft** [katemihalikova/ion-datetime-picker#64] opened 2016-09-19 04:23 UTC
hi, first thank you for the component, I have a question, I'm starting with ionic/angular and I'm trying to set the initial date and time, so far I can do it using the ng-model variable name and then from my controller I do something like...

`$scope.datetimeValue = "2017-01-01";`

that actually update the label but once I click the label to open the popup dialog, the date is not updated and still shows today.

Also once I select a date from the control and the span is updated with the selected date, I don't know how to reset the date, the case is, the user is adding a new task with date and time, after the user save the task I;m looking to clean the form and reset the datetime picker to today's date.

Thanks for your time.

Diego

**Comment by katemihalikova** [comment] 2016-09-19 04:33
Hi Diego,
your first issue seems to be a duplicate of #19 and #14, also please note that the picker is using `Date` instances as a model, nothing else. Your second question is easy, just use assignment again to overwrite the value, i.e. `$scope.datetimeValue = new Date();`.

**Closed by katemihalikova** 2016-09-19 04:33 UTC
Labels: duplicate, question

**Comment by incansoft** [comment] 2016-09-19 04:47
Thanks for your replied I'm going to read those threads.
