### ISSUE TITLE
Returns privious date in  ng-model

### ISSUE THREAD

**Issue by sharad9m** [katemihalikova/ion-datetime-picker#76] opened 2016-10-25 09:43 UTC
When I select date filter shows correct date but date in ng-model is previous date eg. 2016-10-11T18:30:00.000Z when selected date 2016-10-12

**Comment by sharad9m** [comment] 2016-10-25 09:53
How can I set local timezone

**Comment by katemihalikova** [comment] 2016-10-25 10:48
Duplicate of #14 and #15, #24 can be useful too.

**Closed by katemihalikova** 2016-10-25 10:48 UTC
